// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ayJvSaEeL7Y0mpJMjZ3_fjpdEWQafp8',
    appId: '1:348577448582:web:7115dccb4063b0cebc4707',
    messagingSenderId: '348577448582',
    projectId: 'nosrah-44f47',
    authDomain: 'nosrah-44f47.firebaseapp.com',
    storageBucket: 'nosrah-44f47.appspot.com',
    measurementId: 'G-753GLY4NHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJwwkM1w_OQscFsWKIQJ96xVJccR3X4zk',
    appId: '1:348577448582:android:0d62955868c3e598bc4707',
    messagingSenderId: '348577448582',
    projectId: 'nosrah-44f47',
    storageBucket: 'nosrah-44f47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgclGMRL4M4W0bKjT0YwscFnT3X3UeM80',
    appId: '1:348577448582:ios:faf8ce1ee532e895bc4707',
    messagingSenderId: '348577448582',
    projectId: 'nosrah-44f47',
    storageBucket: 'nosrah-44f47.appspot.com',
    iosClientId: '348577448582-3j4pgh329ohq7a998b0lokelqobdr6o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.nosrah',
  );
}
